# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/modeltech64_2020.4/win64
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.cache/wt [current_project]
set_property parent.project_path Y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  Y:/Code/Digital_Design_MCU/Count_down/rtl/bcd7seg.v
  Y:/Code/Digital_Design_MCU/Count_down/rtl/button_debounce.v
  Y:/Code/Digital_Design_MCU/Count_down/rtl/countdown_fsm.v
  Y:/Code/Digital_Design_MCU/Count_down/rtl/decoder_display.v
  Y:/Code/Digital_Design_MCU/Count_down/rtl/top_countdown.v
}
read_ip -quiet Y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all y:/Code/Digital_Design_MCU/Count_down/prj/Count_down/Count_down.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Y:/Code/Digital_Design_MCU/Count_down/xdc/Basys3_Master.xdc
set_property used_in_implementation false [get_files Y:/Code/Digital_Design_MCU/Count_down/xdc/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_countdown -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_countdown.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_countdown_utilization_synth.rpt -pb top_countdown_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
