######################################################################
#
# File name : tb_top_compile.do
# Created on: Fri Jun 13 23:37:47 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../MCU_MOV_shift.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../../../../rtl/adder.v" \
"../../../../../../rtl/alu.v" \
"../../../../../../rtl/arm.v" \
"../../../../../../rtl/condlogic.v" \
"../../../../../../rtl/controller.v" \
"../../../../../../rtl/datapath.v" \
"../../../../../../rtl/decoder.v" \
"../../../../../../rtl/dmem.v" \
"../../../../../../rtl/extend.v" \
"../../../../../../rtl/flopenr.v" \
"../../../../../../rtl/flopr.v" \
"../../../../../../rtl/imem.v" \
"../../../../../../rtl/mux2.v" \
"../../../../../../rtl/regfile.v" \
"../../../../../../rtl/shifter.v" \
"../../../../../../rtl/top.v" \
"../../../../../../sim/tb.v" \


# compile glbl module
E:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

