# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/vivado-project/MCU/prj/SCM_MCU/SCM_MCU.srcs/sources_1/ip/rom_ip_inst/rom_ip_inst.xci
# IP: The module: 'rom_ip_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado-project/MCU/prj/SCM_MCU/SCM_MCU.srcs/sources_1/ip/rom_ip_inst/rom_ip_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_ip_inst'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/vivado-project/MCU/prj/SCM_MCU/SCM_MCU.srcs/sources_1/ip/rom_ip_inst/rom_ip_inst.xci
# IP: The module: 'rom_ip_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado-project/MCU/prj/SCM_MCU/SCM_MCU.srcs/sources_1/ip/rom_ip_inst/rom_ip_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_ip_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
