######################################################################
#
# File name : tb_top_wave.do
# Created on: Fri Jun 13 22:01:27 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
