######################################################################
#
# File name : tb_top_wave.do
# Created on: Sat Jul 05 03:33:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
