set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN W7 [get_ports {seg_output[7]}]
set_property PACKAGE_PIN W6 [get_ports {seg_output[6]}]
set_property PACKAGE_PIN U8 [get_ports {seg_output[5]}]
set_property PACKAGE_PIN V8 [get_ports {seg_output[4]}]
set_property PACKAGE_PIN U5 [get_ports {seg_output[3]}]
set_property PACKAGE_PIN V5 [get_ports {seg_output[2]}]
set_property PACKAGE_PIN U7 [get_ports {seg_output[1]}]
set_property PACKAGE_PIN V7 [get_ports {seg_output[0]}]
set_property PACKAGE_PIN W4 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN V4 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN U4 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN U2 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN R2 [get_ports {switch_input[3]}]
set_property PACKAGE_PIN T1 [get_ports {switch_input[2]}]
set_property PACKAGE_PIN U1 [get_ports {switch_input[1]}]
set_property PACKAGE_PIN W2 [get_ports {switch_input[0]}]
set_property PACKAGE_PIN W19 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
