######################################################################
#
# File name : tb_top_simulate.do
# Created on: Fri Jun 06 20:59:41 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_4 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_top_wave.do}

view wave
view structure
view signals

do {tb_top.udo}

run 1000ns
