# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/Code/Digital_Design_MCU/v200_MCU_multi/prj/prj2019/v200_MCU_multi/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2.xci
# IP: The module: 'imem_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/Digital_Design_MCU/v200_MCU_multi/prj/prj2019/v200_MCU_multi/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: y:/Code/Digital_Design_MCU/v200_MCU_multi/prj/prj2019/v200_MCU_multi/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2.xci
# IP: The module: 'imem_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Code/Digital_Design_MCU/v200_MCU_multi/prj/prj2019/v200_MCU_multi/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
