######################################################################
#
# File name : tb_top_wave.do
# Created on: Tue Jun 17 19:19:13 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
