######################################################################
#
# File name : tb_top_wave.do
# Created on: Wed Jun 18 13:22:51 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
