# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/modeltech64_2020.4/win64
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Y:/Code/Digital_Design_MCU/MCU_test/prj/MCU_test/MCU_test.cache/wt [current_project]
set_property parent.project_path Y:/Code/Digital_Design_MCU/MCU_test/prj/MCU_test/MCU_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo y:/Code/Digital_Design_MCU/MCU_test/prj/MCU_test/MCU_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files Y:/Code/Digital_Design_MCU/MCU_test/sim/memfile.coe
read_verilog -library xil_defaultlib {
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/adder.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/alu.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/arm.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/condlogic.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/controller.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/datapath.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/decoder.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/dmem.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/extend.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/flopenr.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/flopr.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/imem.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/mux2.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/regfile.v
  Y:/Code/Digital_Design_MCU/MCU_test/rtl/top.v
}
read_ip -quiet Y:/Code/Digital_Design_MCU/MCU_test/prj/MCU_test/MCU_test.srcs/sources_1/ip/rom/rom.xci
set_property used_in_implementation false [get_files -all y:/Code/Digital_Design_MCU/MCU_test/prj/MCU_test/MCU_test.srcs/sources_1/ip/rom/rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Y:/Code/Digital_Design_MCU/MCU_test/xdc/Basys3_Master.xdc
set_property used_in_implementation false [get_files Y:/Code/Digital_Design_MCU/MCU_test/xdc/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
