######################################################################
#
# File name : tb_top_wave.do
# Created on: Fri Jul 04 02:32:05 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
