######################################################################
#
# File name : tb_top_compile.do
# Created on: Fri Jul 04 02:43:45 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../v200_MCU_multi.srcs/sources_1/ip/clk_wiz_0" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_7/sim/imem_7.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_6/sim/imem_6.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_5/sim/imem_5.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_4/sim/imem_4.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_3/sim/imem_3.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_2/sim/imem_2.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_1/sim/imem_1.v" \
"../../../../v200_MCU_multi.srcs/sources_1/ip/imem_0/sim/imem_0.v" \

E:\\modeltech64_2020.4\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../v200_MCU_multi.srcs/sources_1/ip/mult_gen_0/sim/mult_gen_0.vhd" \

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../v200_MCU_multi.srcs/sources_1/ip/clk_wiz_0" \
"../../../../../../../rtl/adder.v" \
"../../../../../../../rtl/alu.v" \
"../../../../../../../rtl/arm.v" \
"../../../../../../../rtl/condlogic.v" \
"../../../../../../../rtl/controller.v" \
"../../../../../../../rtl/datapath.v" \
"../../../../../../../rtl/decoder.v" \
"../../../../../../../rtl/dmem.v" \
"../../../../../../../rtl/extend.v" \
"../../../../../../../rtl/flopenr.v" \
"../../../../../../../rtl/flopr.v" \
"../../../../../../../rtl/mux2.v" \
"../../../../../../../rtl/mux3.v" \
"../../../../../../../rtl/regfile.v" \
"../../../../../../../rtl/shifter.v" \
"../../../../../../../rtl/top.v" \
"../../../../../../../sim/tb.v" \

# compile glbl module
E:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

