######################################################################
#
# File name : tb_top_wave.do
# Created on: Sat Jun 14 01:31:37 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
