# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/GitHub/Digital_Design_MCU-main/v210_MCU_multi_32/prj/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2.xci
# IP: The module: 'imem_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/Digital_Design_MCU-main/v210_MCU_multi_32/prj/v200_MCU_multi.gen/sources_1/ip/imem_2/imem_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/GitHub/Digital_Design_MCU-main/v210_MCU_multi_32/prj/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2.xci
# IP: The module: 'imem_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/Digital_Design_MCU-main/v210_MCU_multi_32/prj/v200_MCU_multi.gen/sources_1/ip/imem_2/imem_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
