# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/xdc/Basys3_Master.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
