# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 8
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.cache/wt [current_project]
set_property parent.project_path F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/FFT_input.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/memfile.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_0.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_1.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_2.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_3.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_4.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_5.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_7.coe
add_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/sim/cpu_6.coe
read_verilog -library xil_defaultlib {
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/adder.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/alu.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/arm.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/condlogic.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/controller.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/datapath.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/decoder.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/dmem.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/extend.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/flopenr.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/flopr.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/mux2.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/mux3.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/regfile.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/shifter.v
  F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/rtl/top.v
}
read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
set_property is_enabled true [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_0/imem_0.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_0/imem_0_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_1/imem_1.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_1/imem_1_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_2/imem_2.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_2/imem_2_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_3/imem_3.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_3/imem_3_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_4/imem_4.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_4/imem_4_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_5/imem_5.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_5/imem_5_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_6/imem_6.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_6/imem_6_ooc.xdc]

read_ip -quiet F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.srcs/sources_1/ip/imem_7/imem_7.xci
set_property is_enabled false [get_files -all f:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/prj/v200_MCU_multi.gen/sources_1/ip/imem_7/imem_7_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/xdc/Basys3_Master.xdc
set_property used_in_implementation false [get_files F:/GitHub/Digital_Design_MCU-main/v200_MCU_multi/xdc/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tcpg236-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5 -max_dsp 0
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
