######################################################################
#
# File name : tb_bit8_adder_simulate.do
# Created on: Fri May 16 16:11:45 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_bit8_adder xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_bit8_adder_wave.do}

view wave
view structure
view signals

do {tb_bit8_adder.udo}

run 1000ns
