######################################################################
#
# File name : tb_bit8_adder_compile.do
# Created on: Fri May 16 14:32:45 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../../rtl/bit1_full_adder.v" \
"../../../../../../rtl/bit8_adder.v" \
"../../../../../../sim/tb_bit8_adder.v" \


# compile glbl module
E:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

