######################################################################
#
# File name : tb_bit8_adder_wave.do
# Created on: Fri Apr 25 17:36:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
