######################################################################
#
# File name : tb_top_compile.do
# Created on: Fri Jul 04 17:54:51 +0800 2025
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
G:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
G:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

G:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

G:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

G:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../../v200_MCU_multi.gen/sources_1/ip/clk_wiz_0" \
"tb_top_time_impl.v" \
"../../../../../../sim/tb.v" \


quit -force

