######################################################################
#
# File name : tb_top_simulate.do
# Created on: Fri Jul 04 17:54:56 +0800 2025
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_top_wave.do}

view wave
view structure
view signals

do {tb_top.udo}

run 1000ns
