######################################################################
#
# File name : tb_top_wave.do
# Created on: Fri Jul 04 17:54:56 +0800 2025
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
