######################################################################
#
# File name : ALU_top_compile.do
# Created on: Thu May 22 23:46:02 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../../rtl/pre_adder_32.v" \
"../../../../../../sim/tb.v" \


# compile glbl module
E:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

