######################################################################
#
# File name : ALU_top_simulate.do
# Created on: Thu May 22 23:46:04 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.ALU_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ALU_top_wave.do}

view wave
view structure
view signals

do {ALU_top.udo}

run 1000ns
