######################################################################
#
# File name : ALU_top_wave.do
# Created on: Fri May 16 17:48:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
