######################################################################
#
# File name : mux4_1_32bit_simulate.do
# Created on: Thu May 22 23:25:33 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.mux4_1_32bit xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {mux4_1_32bit_wave.do}

view wave
view structure
view signals

do {mux4_1_32bit.udo}

run 1000ns
