######################################################################
#
# File name : mux4_1_32bit_wave.do
# Created on: Thu May 22 23:24:10 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
