######################################################################
#
# File name : tb_ALU_top_wave.do
# Created on: Sat May 17 11:00:36 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
