######################################################################
#
# File name : tb_ALU_top_simulate.do
# Created on: Fri May 23 00:02:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_ALU_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ALU_top_wave.do}

view wave
view structure
view signals

do {tb_ALU_top.udo}

run 1000ns
